### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by debck**
Added link to get more data

### CODE REVIEW

**Comment by sr6033** [comment]
Change the image. It will be better if you create an art by yourself. Check the readme of my **LTERM** project for reference.

**Comment by debck** [comment]
sry it was by mistake ..ignore the update

**Comment by debck** [comment]
actually "cryptography " is a long word .shall i make it "crypto ."

**Comment by debck** [comment]
plz open in editor and check that

**Comment by sr6033** [comment]
Try with "." and "-".

**Pull request merged**
